/**
 * Turns the ONS borough boundaries into SVG paths for the fill-in map.
 *
 *   pnpm build:boroughs
 *
 * Reads scripts/data/london-boroughs.geojson (downloaded by seed-pubs, and
 * gitignored) and writes src/lib/boroughs.ts, which is committed. Rerun only
 * if the boundaries change, which is roughly never.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const INPUT = join(HERE, 'data', 'london-boroughs.geojson');
const OUTPUT = join(HERE, '..', 'src', 'lib', 'boroughs.ts');

const WIDTH = 1000;
const TOLERANCE = 1.2; // simplification, in output units

type Point = [number, number];
type Feature = {
  properties: { LAD24NM: string; LAD24CD: string };
  geometry: { type: 'Polygon' | 'MultiPolygon'; coordinates: number[][][] | number[][][][] };
};

const geojson = JSON.parse(readFileSync(INPUT, 'utf8')) as { features: Feature[] };

// Bounding box in degrees, then an equirectangular projection scaled so the
// map is not squashed: one degree of longitude at 51.5°N is cos(51.5°) of a
// degree of latitude.
let minLng = Infinity, maxLng = -Infinity, minLat = Infinity, maxLat = -Infinity;
const every = (feature: Feature, fn: (p: Point) => void) => {
  const polys =
    feature.geometry.type === 'Polygon'
      ? [feature.geometry.coordinates as number[][][]]
      : (feature.geometry.coordinates as number[][][][]);
  for (const poly of polys) for (const ring of poly) for (const [lng, lat] of ring) fn([lng, lat]);
};
for (const f of geojson.features) {
  every(f, ([lng, lat]) => {
    minLng = Math.min(minLng, lng); maxLng = Math.max(maxLng, lng);
    minLat = Math.min(minLat, lat); maxLat = Math.max(maxLat, lat);
  });
}
const midLat = (minLat + maxLat) / 2;
const kx = Math.cos((midLat * Math.PI) / 180);
const scale = WIDTH / ((maxLng - minLng) * kx);
const HEIGHT = Math.round((maxLat - minLat) * scale);

const project = ([lng, lat]: Point): Point => [
  (lng - minLng) * kx * scale,
  (maxLat - lat) * scale,
];

// Douglas-Peucker.
function simplify(points: Point[], tolerance: number): Point[] {
  if (points.length < 3) return points;
  const sq = tolerance * tolerance;
  const keep = new Array<boolean>(points.length).fill(false);
  keep[0] = keep[points.length - 1] = true;
  const stack: [number, number][] = [[0, points.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop()!;
    let worst = -1, worstIndex = -1;
    for (let i = a + 1; i < b; i += 1) {
      const d = segDistSq(points[i], points[a], points[b]);
      if (d > worst) { worst = d; worstIndex = i; }
    }
    if (worst > sq) {
      keep[worstIndex] = true;
      stack.push([a, worstIndex], [worstIndex, b]);
    }
  }
  return points.filter((_, i) => keep[i]);
}
function segDistSq(p: Point, a: Point, b: Point): number {
  let [x, y] = a;
  let dx = b[0] - x, dy = b[1] - y;
  if (dx !== 0 || dy !== 0) {
    const t = ((p[0] - x) * dx + (p[1] - y) * dy) / (dx * dx + dy * dy);
    if (t > 1) { x = b[0]; y = b[1]; } else if (t > 0) { x += dx * t; y += dy * t; }
  }
  dx = p[0] - x; dy = p[1] - y;
  return dx * dx + dy * dy;
}

const fmt = (n: number) => n.toFixed(1).replace(/\.0$/, '');

const boroughs = geojson.features
  .map((feature) => {
    const polys =
      feature.geometry.type === 'Polygon'
        ? [feature.geometry.coordinates as number[][][]]
        : (feature.geometry.coordinates as number[][][][]);
    let d = '';
    let sx = 0, sy = 0, n = 0;
    for (const poly of polys) {
      for (const ring of poly) {
        const pts = simplify(ring.map(([lng, lat]) => project([lng, lat])), TOLERANCE);
        d += pts.map(([x, y], i) => `${i ? 'L' : 'M'}${fmt(x)} ${fmt(y)}`).join('') + 'Z';
      }
      // label position: centroid of the outer ring's vertices, good enough
      for (const [lng, lat] of poly[0]) { const [x, y] = project([lng, lat]); sx += x; sy += y; n += 1; }
    }
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    for (const poly of polys) for (const ring of poly) for (const [lng, lat] of ring) {
      const [x, y] = project([lng, lat]);
      minX = Math.min(minX, x); maxX = Math.max(maxX, x); minY = Math.min(minY, y); maxY = Math.max(maxY, y);
    }
    return {
      name: feature.properties.LAD24NM,
      d,
      cx: Math.round(sx / n),
      cy: Math.round(sy / n),
      bbox: [minX, minY, maxX, maxY].map((v) => Math.round(v * 10) / 10) as [number, number, number, number],
    };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

const out = `// Generated by scripts/build-boroughs.ts from ONS Local Authority Districts
// (December 2024) BGC, filtered to the London boroughs. Do not edit by hand.
// Contains OS data © Crown copyright and database right 2024.
// Contains National Statistics data © Crown copyright and database right 2024.

export const BOROUGH_VIEWBOX = '0 0 ${WIDTH} ${HEIGHT}';

export type BoroughShape = {
  name: string;
  d: string;
  cx: number;
  cy: number;
  /** minX, minY, maxX, maxY in viewBox units */
  bbox: [number, number, number, number];
};

/** Equirectangular projection used for every path. lng/lat to viewBox x/y. */
export const BOROUGH_PROJECTION = { minLng: ${minLng}, maxLat: ${maxLat}, kx: ${kx}, scale: ${scale} };

export function projectToBoroughMap(lng: number, lat: number): [number, number] {
  const { minLng, maxLat, kx, scale } = BOROUGH_PROJECTION;
  return [(lng - minLng) * kx * scale, (maxLat - lat) * scale];
}

export const BOROUGHS: BoroughShape[] = ${JSON.stringify(boroughs, null, 2)};
`;

writeFileSync(OUTPUT, out);
console.log(`wrote ${boroughs.length} boroughs, ${(out.length / 1024).toFixed(0)} KB, viewBox ${WIDTH}x${HEIGHT}`);
